### PR TITLE
Updated API to support the latest node.

### PR DESCRIPTION
**Pull request by kalouantonis**
Hi,

First, I'd really like to thank you for creating an awesome library that's saved me hours worth of work.

I have issues using the library for the latest node however, so I re-wrote the bindings. As far as I've tested, they seem to work in the same way, but I've never written bindings to Node before, so I may be missing something, feel free to point it out and I'll fix it.

I've changed the release version from 0.1.x to 0.2.0, so if you do decide to pull, perhaps it would be better to create a new release.

Regards,
Antonis.

### CODE REVIEW

**Comment by lrz** [comment]
Antonis, thank you so much for the pull request! Glad to see that the project is useful to other people :-) However, would you mind to re-submit that pull request without indentation changes? (especially in the C++ code).

**Comment by kalouantonis** [comment]
I hope this fixes it.

**Comment by kalouantonis** [comment]
Travis fails because I'm using C++11 features, I can revert to just standard C++ if that's a problem.

**Comment by bruce** [comment]
Superseded by #22.

**Pull request closed without merging**
